# Generated by Django 5.1.2 on 2025-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='unique_identifier',
        ),
        migrations.AddField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
