# Generated by Django 5.1.2 on 2024-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255, unique=True)),
                ('win_id', models.CharField(max_length=100)),
                ('los_id', models.CharField(max_length=100)),
                ('winner_boards', models.JSONField(default=list)),
                ('num_of_games', models.IntegerField(default=0)),
                ('first_to', models.IntegerField(default=1)),
            ],
        ),
    ]
