# Generated by Django 5.1.4 on 2024-12-25 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255, unique=True)),
                ('winner_boards', models.JSONField(default=list)),
                ('num_of_games', models.IntegerField(default=0)),
                ('game_type_db', models.JSONField(default=list)),
                ('p1id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('p2id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('winid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
